S3_BUCKET = "s3://trafik"
CITIES = ["berlin", "istanbul"]
PROCESSED_DIR = "processed"
TRAINING_DIR = "training"
VALIDATION_DIR = "validation"
TESTING_DIR = "testing"
INTERMEDIATE_DIR = "intermediate"
MAX_VOLUME = "max_volume"
AVG_TOTAL_VOLUME = "avg_total_volume"
modes = [TRAINING_DIR, VALIDATION_DIR, TESTING_DIR]
